spring:
  datasource:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password: 1234
  thymeleaf:
    view-names: "views/*"
    prefix: "/WEB-INF/"
server:
  servlet:
    context-path: /order
kdt:
  version: "v1.0-default"
  minimum-order-amount: 1
  support-vendors:
    - default
  description: |-
    line 1 default
    line 2 default
